This file contains the information gathered from several water monitoring stations in a lake system. Unfortunately, the results had been assembled by hand and is messy.

 

Create a Jupyter Notebook and submit a program which does the follow:

Reads in the data and cleans it
Uses the cleaned data as data for an object oriented program that contains at least 2 classes
 

Think carefully about what these classes should look like and do. Be sure to show how these classes are used. Full credit will be awarded for creative, non-trivial implementations. Use markdown cells to explain your thought process. Good coding style should be used.

In [68]:
import pandas as pd

#reading in the csv file
water = pd.read_csv('water_quality_readings.csv')
#replaced the the NaN with 0 instead of using dropna that would leave out row 15 and row 9
water = water.fillna(0)

#finding and replacing the errors from the file
#water = water[water['time']].replace([';'],':')
#water.drop(['30','31'])
water.at[15, 'time'] = '9:05'
water.at[26, 'temperature'] = '67.1'
#noticed that station number was spelt wrong and had to change the name
water.rename(columns={'station numer': 'station_number'}, inplace = True)
#changed the names so it would be easier to use during my class sections
water.rename(columns={'ph reading': 'ph_reading'}, inplace = True)
water.rename(columns={'dissolved oxygen': 'dissolved_oxygen'}, inplace = True)
water

    station_number       date   time  ph_reading  dissolved_oxygen temperature
0              1.0   4/1/2023  11:58        8.92             8.887        65.4
1              3.0   4/2/2023  14:32        7.66             8.402        73.4
2              4.0   4/3/2023   8:44        8.09             7.150        74.9
3              2.0   4/4/2023   9:02        7.90             8.559        70.8
4              1.0   4/5/2023  10:58        6.44             6.590        69.0
5              5.0   4/6/2023  13:32        8.75             6.453        66.5
6              2.0   4/7/2023  10:44        8.66             7.844        66.1
7              1.0   4/7/2023  11:02        8.16             8.527        70.4
8              4.0   4/7/2023  11:58        8.36             7.641        66.1
9              5.0   4/8/2023  15:32        6.73             0.000        69.2
10             1.0  4/10/2023   8:42        8.51             8.489        67.7
11             3.0  4/10/2023   9:15        6.81             8.042        73.5
12             2.0  4/11/2023  12:58        6.05             8.123        73.9
13             4.0  4/11/2023  13:32        7.81             6.808        73.7
14             5.0  4/11/2023   7:47        7.50             7.751        71.4
15             2.0  4/12/2023   9:05        6.32             7.375        70.2
16             3.0  4/12/2023  11:11        6.68             7.123        66.1
17             1.0  4/12/2023  14:22        6.78             7.711        71.6
18             0.0  4/12/2023   8:47        8.67             8.405        70.0
19             5.0  4/13/2023   9:01        8.17             8.369        70.8
20             4.0  4/13/2023  10:33        7.39             6.784        71.6
21             3.0  4/13/2023  14:32        7.18             6.313        65.3
22             2.0  4/13/2023   9:41        6.10             7.200        69.8
23             1.0  4/14/2023   9:02        7.36             8.329        72.1
24             2.0  4/14/2023  11:59        8.11             7.308        65.7
25             4.0  4/14/2023  13:31        8.19             8.885        70.5
26             3.0  4/14/2023   8:14        7.05             8.430        67.1
27             5.0  4/14/2023   9:05        7.78             8.596        68.6
28             1.0  4/15/2023   9:15        7.43             7.348        68.3
29             5.0  4/15/2023  16:45        8.18             7.244        68.0
30             0.0          0      0        0.00             0.000           0
31             0.0          0      0        0.00             0.000           0

In [73]:
#ploting a graph of the data to show the dates for ph and how they are to get an average
water2 = water.index_col = 'date'
water2.drop(['time','dissolved_oxygen','temperature'])
water2_plot = water2.plot(kind="bar",cmap="Blues",ylim=(0,150),figsize=(14,4), color = 'blue')
water2_plot.figure.suptitle("Water levels")
water2_plot.set_xlabel("Date checked",fontweight="bold")
water2_plot.set_ylabel("Ph Reading",fontweight="bold")

AttributeError: 'str' object has no attribute 'drop'

In [75]:
from functools import total_ordering 


#my water class is going to be the parent class
class wtr():
    
    #this init function is the initializer for the class
    def __init__(self, wtr, station_number, date, time, ph_reading, dissolved_oxygen,temperature):
        self.wtr = wtr
        self.station_number = station_number
        self.date = date
        self.time = time
        self.ph_reading = ph_reading
        self.dissolved_oxygen = dissolved_oxygen
        self.temperature = temperature
        
        
    #this method function is for   
    #def __method__(self, wtr):
        #print(self.wtr)
    
     #this function identifies if it is a string    
    def __str__(self,station_number, date, time, ph_reading, dissolved_oxygen,temperature):
        return self.station_number, self.date, self.time, self.ph_reading, self.dissolved_oxygen, self.temperature
    
    #this fuction identifies if they are equal
    def __eq__(self, other):
        return self.wtr == other.wtr

#my child class
class olympic(wtr):
    #this init function allows me to use the vlaues in my parent class above 
    def __init__(self, wtr, station_number, date, time, ph_reading, dissolved_oxygen,temperature):
        wtr.__init__(self, wtr, station_number, date, time, ph_reading, dissolved_oxygen,temperature)
    
    #this init function allows me to use the vlaues in my parent class above 
    def __init__(self, station_number, date, time, ph_reading, dissolved_oxygen,temperature):
        wtr.__init__(self, station_number, date, time, ph_reading, dissolved_oxygen,temperature)
        
    #this function is going to be used for seeing if the pool water has been checked for being safe
    def lastChecked(self,date):
            for i in self.date:
                return f'the last day it was checked was {self.date}'
            
    #this function is going to be used for checking if the ph of the water is safe for use       
    def safePh(self,ph_reading):
        for i in self.ph_reading:
            return f'the ph level for the day is {self.ph_reading}'
        
    #this function is for checking the optimal time the water is great
    def greatDay(self,date, ph_reading,dissolved_oxygen):
        for i in self.ph_reading:
            if i in range(6.5, 8.5):
                for i in self.dissolved_oxygen:
                    if i >= 6.5:
                        print(f'Great for a dive in the pool with {self.ph_reading} ph, {self.dissolved_oxygen} oxygen per mg/L on {self.date}'
    
    #this function is for checking the temperature of the pool
    def weather(self,temperature):
        for i in self.temperature >= 70:
            print(f'This is above room temperature at {self.temperature} degrees')
        for i in self.temperature <= 70:
            print(f'This is below room temperature at {self.temperature} degrees')

SyntaxError: invalid syntax (3788980735.py, line 59)